"""AI-powered glossary generation service.

Generates project-specific glossary definitions using LLM calls during sync.
Processes each changed document (or chunk) in a single LLM pass, extracting
and defining all glossary-worthy terms at once. Human edits to existing
definitions in glossary.md are preserved verbatim.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING

from nest.core.models import AIGlossaryResult
from nest.core.paths import GLOSSARY_TABLE_END, GLOSSARY_TABLE_START

if TYPE_CHECKING:
    from nest.adapters.protocols import FileSystemProtocol, LLMProviderProtocol

logger = logging.getLogger(__name__)

GLOSSARY_SYSTEM_PROMPT = (
    "You are a technical glossary assistant. Given a project document (or a section "
    "of one), extract every term that a consultant or developer joining this project "
    "would need to look up.\n\n"
    "{PROJECT_CONTEXT_BLOCK}\n\n"
    "Extract terms into this EXACT format, one per line, no header row, no other text:\n"
    "| <Term> | <Category> | <Definition> |\n\n"
    "Categories: Acronym, Organization, Product/Platform, Domain Term, Role, "
    "Standard, System\n\n"
    "Rules:\n"
    "- INCLUDE: project-specific acronyms, client/vendor/partner names, named "
    "products and platforms, industry-specific standards, regulatory bodies, "
    "custom roles, integration systems, and any term whose meaning in THIS "
    "project would not be obvious.\n"
    "- EXCLUDE: universally known technical terms (e.g., API, HTTP, JSON, Agile, "
    "CI/CD). The test: would a senior technical consultant already know this "
    "without project context? If yes, exclude it.\n"
    "- Definitions must be at most 10 words, referencing the project context where possible.\n"
    "- For acronyms, include the expansion in the definition.\n"
    "- Do NOT use pipe characters (|) within any cell value.\n"
    "- If no glossary-worthy terms are found, output nothing."
)

VALID_CATEGORIES = {
    "Acronym",
    "Organization",
    "Product/Platform",
    "Domain Term",
    "Role",
    "Standard",
    "System",
}

GLOSSARY_HEADER = (
    "# Project Glossary\n"
    "\n"
    "> Auto-generated by nest sync. Human edits to existing definitions are preserved.\n"
    "\n"
)

GLOSSARY_TABLE_HEADER = "| Term | Category | Definition |\n|------|----------|------------|"

# Default chunk size: ~40K tokens ~ 160K characters
DEFAULT_MAX_CHARS = 160_000


class AIGlossaryService:
    """Generates AI-powered glossary definitions from project documents.

    Processes each changed file (or chunk for large files) in a single LLM
    pass that extracts and defines all glossary-worthy terms. Operates
    incrementally: existing definitions are never modified or deleted.
    """

    def __init__(
        self,
        llm_provider: LLMProviderProtocol,
        filesystem: FileSystemProtocol,
    ) -> None:
        self._llm = llm_provider
        self._fs = filesystem

    def generate(
        self,
        changed_files: list[Path],
        context_dir: Path,
        glossary_path: Path,
        project_context: str | None = None,
    ) -> AIGlossaryResult:
        """Generate glossary definitions from changed project documents.

        Args:
            changed_files: List of changed/new file paths to process.
            context_dir: Path to the _nest_context directory.
            glossary_path: Path to the glossary.md file.
            project_context: Optional project context text.

        Returns:
            AIGlossaryResult with counts and token usage.
        """
        if not changed_files:
            return AIGlossaryResult()

        # Load existing glossary terms (case-insensitive dedup)
        existing_rows, existing_terms = self._load_existing_glossary(glossary_path)

        system_prompt = self._build_system_prompt(project_context)

        terms_added = 0
        terms_skipped_existing = 0
        terms_failed = 0
        files_processed = 0
        chunks_processed = 0
        prompt_tokens = 0
        completion_tokens = 0
        new_rows: list[str] = []
        already_extracted: set[str] = set()

        for file_path in changed_files:
            try:
                content = self._fs.read_text(file_path)
            except Exception:
                logger.warning("Failed to read file for glossary: %s", file_path)
                terms_failed += 1
                continue

            if not content.strip():
                files_processed += 1
                continue

            chunks = self._chunk_content(content)
            files_processed += 1

            for chunk in chunks:
                chunks_processed += 1
                result = self._llm.complete(system_prompt, chunk)

                if result is None:
                    logger.warning("AI glossary LLM call failed for file: %s", file_path)
                    terms_failed += 1
                    continue

                prompt_tokens += result.prompt_tokens
                completion_tokens += result.completion_tokens

                parsed_rows = self._parse_table_rows(result.text)

                for term, category, definition in parsed_rows:
                    term_lower = term.lower()
                    if term_lower in existing_terms or term_lower in already_extracted:
                        terms_skipped_existing += 1
                        continue

                    row = f"| {term} | {category} | {definition} |"
                    new_rows.append(row)
                    already_extracted.add(term_lower)
                    terms_added += 1

        # Write glossary if we have new terms
        if new_rows:
            self._write_glossary(glossary_path, existing_rows, new_rows)

        return AIGlossaryResult(
            terms_added=terms_added,
            terms_skipped_existing=terms_skipped_existing,
            terms_failed=terms_failed,
            files_processed=files_processed,
            chunks_processed=chunks_processed,
            prompt_tokens=prompt_tokens,
            completion_tokens=completion_tokens,
        )

    @staticmethod
    def _build_system_prompt(project_context: str | None = None) -> str:
        """Build system prompt, optionally inserting project context.

        Args:
            project_context: Optional project context text to prepend.

        Returns:
            Formatted system prompt string.
        """
        if project_context:
            context_block = f"Project context:\n{project_context}"
        else:
            context_block = ""
        return GLOSSARY_SYSTEM_PROMPT.replace("{PROJECT_CONTEXT_BLOCK}", context_block)

    @staticmethod
    def _chunk_content(content: str, max_chars: int = DEFAULT_MAX_CHARS) -> list[str]:
        """Split content into chunks on paragraph boundaries.

        Args:
            content: Full document content.
            max_chars: Maximum characters per chunk.

        Returns:
            List of content chunks.
        """
        if len(content) <= max_chars:
            return [content]

        paragraphs = content.split("\n\n")
        chunks: list[str] = []
        current_chunk: list[str] = []
        current_len = 0

        for para in paragraphs:
            para_len = len(para) + 2  # account for \n\n separator
            if current_len + para_len > max_chars and current_chunk:
                chunks.append("\n\n".join(current_chunk))
                current_chunk = [para]
                current_len = len(para)
            else:
                current_chunk.append(para)
                current_len += para_len

        if current_chunk:
            chunks.append("\n\n".join(current_chunk))

        return chunks

    @staticmethod
    def _parse_table_rows(text: str) -> list[tuple[str, str, str]]:
        """Parse LLM response into list of (term, category, definition) tuples.

        Args:
            text: Raw LLM response text.

        Returns:
            List of (term, category, definition) tuples.
        """
        results: list[tuple[str, str, str]] = []
        for line in text.strip().splitlines():
            line = line.strip()
            if not line.startswith("|"):
                continue
            cols = line.split("|")
            if len(cols) < 4:
                continue
            term = cols[1].strip()
            category = cols[2].strip()
            definition = cols[3].strip()

            # Skip header/separator rows
            if not term or term == "Term" or term.startswith("---"):
                continue
            if category.startswith("---") or definition.startswith("---"):
                continue

            # Validate category
            if category not in VALID_CATEGORIES:
                category = "Domain Term"

            # Sanitize and truncate definition
            definition = AIGlossaryService._sanitize_definition(definition)
            definition = AIGlossaryService._truncate_definition(definition)

            if definition:
                results.append((term, category, definition))

        return results

    @staticmethod
    def _sanitize_definition(text: str) -> str:
        """Sanitize definition text for Markdown table safety.

        Args:
            text: Raw definition text.

        Returns:
            Sanitized definition string.
        """
        return text.replace("\n", " ").replace("|", "-").strip().strip('"').strip("'").strip()

    @staticmethod
    def _truncate_definition(text: str, max_words: int = 10) -> str:
        """Truncate definition to max_words.

        Args:
            text: Sanitized definition text.
            max_words: Maximum number of words.

        Returns:
            Truncated definition string.
        """
        words = text.split()
        if len(words) > max_words:
            return " ".join(words[:max_words])
        return text

    def _load_existing_glossary(self, glossary_path: Path) -> tuple[list[str], set[str]]:
        """Load existing glossary.md and parse defined terms.

        Args:
            glossary_path: Path to glossary.md file.

        Returns:
            Tuple of (existing_table_rows, set_of_defined_term_names).
        """
        existing_rows: list[str] = []
        existing_terms: set[str] = set()

        if not self._fs.exists(glossary_path):
            return existing_rows, existing_terms

        content = self._fs.read_text(glossary_path)
        in_table = False
        for line in content.splitlines():
            stripped = line.strip()
            if stripped == GLOSSARY_TABLE_START:
                in_table = True
                continue
            if stripped == GLOSSARY_TABLE_END:
                in_table = False
                continue
            if in_table and stripped.startswith("|"):
                cols = stripped.split("|")
                if len(cols) >= 3:
                    term = cols[1].strip()
                    if term and term != "Term" and not term.startswith("---"):
                        existing_terms.add(term.lower())
                        existing_rows.append(stripped)

        return existing_rows, existing_terms

    def _write_glossary(
        self,
        glossary_path: Path,
        existing_rows: list[str],
        new_rows: list[str],
    ) -> None:
        """Write glossary.md with all rows sorted alphabetically.

        Args:
            glossary_path: Path to glossary.md file.
            existing_rows: Existing table rows from glossary.
            new_rows: New table rows to add.
        """
        all_rows = existing_rows + new_rows
        all_rows.sort(key=lambda row: row.split("|")[1].strip().lower())

        content = (
            GLOSSARY_HEADER
            + GLOSSARY_TABLE_START
            + "\n"
            + GLOSSARY_TABLE_HEADER
            + "\n"
            + "\n".join(all_rows)
            + "\n"
            + GLOSSARY_TABLE_END
            + "\n"
        )

        self._fs.write_text(glossary_path, content)
