"""E2E tests for glossary agent integration (Story 5.2).

Tests verify glossary hints generation during sync, agent template
creation during init, hints file exclusion from index, and incremental
processing. These tests use passthrough text files (no Docling needed).
"""

from pathlib import Path

import pytest
import yaml

from .conftest import run_cli


@pytest.mark.e2e
class TestGlossaryE2E:
    """E2E tests for glossary hints and agent integration."""

    def test_sync_generates_glossary_hints(self, initialized_project: Path) -> None:
        """AC1: After sync with documents containing abbreviations, 00_GLOSSARY_HINTS.yaml exists.

        1. Add a source file with known abbreviations
        2. Run nest sync
        3. Assert _nest_context/00_GLOSSARY_HINTS.yaml exists
        4. Parse YAML, verify structure has 'terms' list
        5. Verify entries have: term, category, occurrences, source_files, context_snippets
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create a file with multiple abbreviation occurrences (>= 2 for threshold)
        content = (
            "The PDC review board meets weekly to approve milestones.\n"
            "PDC members include the VP and the SOW author.\n"
            "The SOW defines the project scope and deliverables.\n"
            "Our SME provided technical guidance for the PDC.\n"
            "The SME also reviewed the final SOW draft.\n"
        )
        (sources_dir / "contracts" / "alpha.md").parent.mkdir(parents=True, exist_ok=True)
        (sources_dir / "contracts" / "alpha.md").write_text(content)

        # Run sync
        result = run_cli(["sync"], cwd=project_dir)
        assert result.exit_code == 0, f"Sync failed: {result.stderr}\n{result.stdout}"

        # Assert glossary hints file exists
        hints_path = project_dir / ".nest" / "00_GLOSSARY_HINTS.yaml"
        assert hints_path.exists(), "00_GLOSSARY_HINTS.yaml should exist after sync"

        # Parse and validate structure
        hints_content = hints_path.read_text()
        assert "Auto-generated by nest sync" in hints_content

        hints_data = yaml.safe_load(hints_content)
        assert "terms" in hints_data
        assert len(hints_data["terms"]) > 0

        # Check that at least one term has required fields
        for term_entry in hints_data["terms"]:
            assert "term" in term_entry
            assert "category" in term_entry
            assert "occurrences" in term_entry
            assert "source_files" in term_entry
            assert "context_snippets" in term_entry

        # PDC should be detected (appears 3 times, above threshold)
        pdc_entries = [t for t in hints_data["terms"] if t["term"] == "PDC"]
        assert len(pdc_entries) == 1, "PDC should be detected as a candidate term"
        assert pdc_entries[0]["category"] == "abbreviation"
        assert pdc_entries[0]["occurrences"] >= 2

    def test_glossary_hints_excluded_from_index(self, initialized_project: Path) -> None:
        """AC8: 00_GLOSSARY_HINTS.yaml must not appear in the master index.

        1. Add source with abbreviations, run sync
        2. Read 00_MASTER_INDEX.md
        3. Assert "00_GLOSSARY_HINTS.yaml" is NOT in the table
        4. Assert glossary.md IS included if present
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        (sources_dir / "doc.md").write_text("The XYZ committee meets. XYZ reviews.\n")

        result = run_cli(["sync"], cwd=project_dir)
        assert result.exit_code == 0, f"Sync failed: {result.stderr}\n{result.stdout}"

        # Read master index
        index_path = project_dir / ".nest" / "00_MASTER_INDEX.md"
        assert index_path.exists()
        index_content = index_path.read_text()

        # 00_GLOSSARY_HINTS.yaml must NOT appear in the index
        assert "00_GLOSSARY_HINTS.yaml" not in index_content

    def test_glossary_agent_created_on_init(self, fresh_temp_dir: Path) -> None:
        """AC4: nest init creates .github/agents/nest-glossary.agent.md.

        1. Run nest init "Test"
        2. Assert .github/agents/nest-glossary.agent.md exists
        3. Assert file contains "00_GLOSSARY_HINTS.yaml" reference
        4. Assert file contains "glossary.md" reference
        """
        result = run_cli(["init", "GlossaryTestProject"], cwd=fresh_temp_dir)
        assert result.exit_code == 0, f"Init failed: {result.stderr}\n{result.stdout}"

        agent_path = fresh_temp_dir / ".github" / "agents" / "nest-glossary.agent.md"
        assert agent_path.exists(), "nest-glossary.agent.md should be created by init"

        content = agent_path.read_text()
        assert "00_GLOSSARY_HINTS.yaml" in content
        assert "glossary.md" in content
        assert "GlossaryTestProject" in content
        assert "nest-glossary" in content

    def test_glossary_hints_incremental(self, initialized_project: Path) -> None:
        """AC3: Only new/modified files are re-scanned on subsequent syncs.

        1. Add source, run sync
        2. Record hints state
        3. Run sync again (no changes)
        4. Verify hints are preserved without re-scanning
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create file with terms and sync
        (sources_dir / "doc.md").write_text("The PDC board meets. PDC reviews.\n")
        result1 = run_cli(["sync"], cwd=project_dir)
        assert result1.exit_code == 0

        # Read first hints
        hints_path = project_dir / ".nest" / "00_GLOSSARY_HINTS.yaml"
        assert hints_path.exists()
        first_hints = hints_path.read_text()

        # Run sync again — no changes
        result2 = run_cli(["sync"], cwd=project_dir)
        assert result2.exit_code == 0

        # Hints should still exist and have same terms
        second_hints = hints_path.read_text()
        first_data = yaml.safe_load(first_hints)
        second_data = yaml.safe_load(second_hints)

        first_terms = {t["term"] for t in first_data.get("terms", [])}
        second_terms = {t["term"] for t in second_data.get("terms", [])}
        assert first_terms == second_terms, "Terms should be preserved across syncs"

    def test_sync_output_shows_glossary_prompt(self, initialized_project: Path) -> None:
        """AC7: Sync output should show glossary terms message when terms discovered."""
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create file with enough abbreviation occurrences
        (sources_dir / "doc.md").write_text(
            "The PDC meets weekly. PDC members review. PDC reports.\n"
            "The SOW is signed. SOW defines scope. SOW appendix.\n"
        )

        result = run_cli(["sync"], cwd=project_dir)
        assert result.exit_code == 0

        # Should show glossary prompt in output
        assert "candidate glossary term" in result.stdout
        assert "@nest-glossary" in result.stdout
