"""E2E tests for the index enrichment pipeline (Story 5.1).

Tests verify table format index, hints file generation,
and description preservation/clearing.
These tests use passthrough text files (no Docling needed).
"""

from pathlib import Path

import pytest
import yaml

from .conftest import run_cli


@pytest.mark.e2e
class TestEnrichmentE2E:
    """E2E tests for index enrichment pipeline."""

    def test_sync_generates_table_format_index(self, initialized_project: Path) -> None:
        """AC1: Master index should use Markdown table format with markers.

        After sync, 00_MASTER_INDEX.md must contain:
        - <!-- nest:index-table-start --> marker
        - <!-- nest:index-table-end --> marker
        - Table header: | File | Lines | Description |
        - Entry rows for synced files
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create a text file
        (sources_dir / "notes.txt").write_text("Meeting notes line 1\nLine 2\n")

        # Run sync
        result = run_cli(["sync"], cwd=project_dir)
        assert result.exit_code == 0, f"Sync failed: {result.stderr}\n{result.stdout}"

        # Read index
        index_path = project_dir / ".nest" / "00_MASTER_INDEX.md"
        assert index_path.exists(), "00_MASTER_INDEX.md should exist"
        index_content = index_path.read_text()

        # Assert table format markers
        assert "<!-- nest:index-table-start -->" in index_content
        assert "<!-- nest:index-table-end -->" in index_content

        # Assert table header
        assert "| File | Lines | Description |" in index_content
        assert "|------|------:|-------------|" in index_content

        # Assert file appears in table
        assert "notes.txt" in index_content

    def test_sync_generates_hints_file(self, initialized_project: Path) -> None:
        """AC2: Sync should create 00_INDEX_HINTS.yaml with file metadata.

        The hints file should contain:
        - A list of files with paths and content hashes
        - Auto-generated header comment
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create files
        (sources_dir / "doc.md").write_text("# My Document\n\nFirst paragraph.\n")
        (sources_dir / "data.csv").write_text("Name,Age,City\nJohn,30,NYC\n")

        # Run sync
        result = run_cli(["sync"], cwd=project_dir)
        assert result.exit_code == 0, f"Sync failed: {result.stderr}\n{result.stdout}"

        # Read hints file
        hints_path = project_dir / ".nest" / "00_INDEX_HINTS.yaml"
        assert hints_path.exists(), "00_INDEX_HINTS.yaml should exist"
        hints_content = hints_path.read_text()

        # Assert header comment
        assert "Auto-generated by nest sync" in hints_content

        # Parse and validate structure
        hints_data = yaml.safe_load(hints_content)
        assert "files" in hints_data
        assert len(hints_data["files"]) >= 2

        # Check doc.md entry
        doc_entry = next(e for e in hints_data["files"] if e["path"] == "doc.md")
        assert "content_hash" in doc_entry
        assert len(doc_entry["content_hash"]) == 16  # 16-char hex hash
        assert doc_entry["lines"] > 0
        assert any(h["text"] == "My Document" for h in doc_entry.get("headings", []))
        assert doc_entry.get("first_paragraph") == "First paragraph."

        # Check data.csv entry has table_columns
        csv_entry = next(e for e in hints_data["files"] if e["path"] == "data.csv")
        assert csv_entry.get("table_columns") == ["Name", "Age", "City"]

    def test_sync_preserves_descriptions_on_unchanged_files(
        self, initialized_project: Path
    ) -> None:
        """AC4: Descriptions should be preserved when file content hasn't changed.

        When the index has a description for a file and the file hasn't changed
        (same content_hash), the description should carry forward after re-sync.
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create file and sync
        (sources_dir / "notes.txt").write_text("Meeting notes content\n")
        result1 = run_cli(["sync"], cwd=project_dir)
        assert result1.exit_code == 0

        # Manually edit index to add a description
        index_path = project_dir / ".nest" / "00_MASTER_INDEX.md"
        content = index_path.read_text()
        # Find the notes.txt row and add a description
        lines = content.splitlines()
        new_lines = []
        for line in lines:
            if "notes.txt" in line and line.startswith("|"):
                parts = line.split("|")
                # parts: ['', ' notes.txt ', ' N ', ' ', '']
                if len(parts) >= 5:
                    parts[-2] = " Custom description for notes "
                    line = "|".join(parts)
            new_lines.append(line)
        index_path.write_text("\n".join(new_lines))

        # Run sync again without changing the source file
        result2 = run_cli(["sync"], cwd=project_dir)
        assert result2.exit_code == 0

        # Check that description was preserved
        index_after = index_path.read_text()
        assert "Custom description for notes" in index_after

    def test_sync_clears_description_on_changed_file(self, initialized_project: Path) -> None:
        """AC5: When a file's content changes, its description should be cleared.

        If the content_hash changes between syncs, the description should be
        reset to empty so the enricher agent can provide a new one.
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create file and sync
        (sources_dir / "notes.txt").write_text("Original content\n")
        result1 = run_cli(["sync"], cwd=project_dir)
        assert result1.exit_code == 0

        # Add a description to the index
        index_path = project_dir / ".nest" / "00_MASTER_INDEX.md"
        content = index_path.read_text()
        lines = content.splitlines()
        new_lines = []
        for line in lines:
            if "notes.txt" in line and line.startswith("|"):
                parts = line.split("|")
                if len(parts) >= 5:
                    parts[-2] = " Old description "
                    line = "|".join(parts)
            new_lines.append(line)
        index_path.write_text("\n".join(new_lines))

        # Modify the source file (content changes → hash changes)
        new_content = "Completely different content now\nWith more lines\n"
        (sources_dir / "notes.txt").write_text(new_content)

        # Re-sync
        result2 = run_cli(["sync"], cwd=project_dir)
        assert result2.exit_code == 0

        # Description should be cleared (empty)
        index_after = index_path.read_text()
        assert "Old description" not in index_after

    def test_hints_file_excluded_from_index(self, initialized_project: Path) -> None:
        """AC6: 00_INDEX_HINTS.yaml should NOT appear as a row in the master index.

        The hints file is an internal artifact and should be excluded from
        the index table listing.
        """
        project_dir = initialized_project
        sources_dir = project_dir / "_nest_sources"

        # Create a file and sync
        (sources_dir / "readme.md").write_text("# README\n\nProject readme.\n")
        result = run_cli(["sync"], cwd=project_dir)
        assert result.exit_code == 0

        # Read index content
        index_path = project_dir / ".nest" / "00_MASTER_INDEX.md"
        index_content = index_path.read_text()

        # Hints file should NOT appear in index table
        # (It may appear in the YAML-related content but not as a table row)
        table_start = index_content.find("<!-- nest:index-table-start -->")
        table_end = index_content.find("<!-- nest:index-table-end -->")
        if table_start != -1 and table_end != -1:
            table_section = index_content[table_start:table_end]
            assert "00_INDEX_HINTS" not in table_section

        # 00_MASTER_INDEX.md itself should also not appear
        if table_start != -1 and table_end != -1:
            assert "00_MASTER_INDEX" not in table_section
