"""E2E tests for image description via vision LLM (Story 7.5).

Tests verify the full image description pipeline using real Docling processing,
subprocess CLI invocation, and a mocked vision LLM HTTP server.  No real API
calls to external vision providers are made in any test.

Mocking strategy
----------------
``MockVisionServer`` starts a local HTTP server on a random port that returns a
canned OpenAI-compatible JSON response for every POST request.  Subprocesses are
launched with env vars (``NEST_AI_API_KEY``, ``NEST_AI_ENDPOINT``, …) pointing
at the mock server, so both text-enrichment and vision LLM calls are handled by
the same in-process stub.

The ``image_doc.pdf`` fixture (generated by
``tests/e2e/fixtures/generate_fixtures.py``) contains one embedded bar-chart
image.  Docling detects it as a ``PictureItem`` with ``label=bar_chart``.
"""

import json
import shutil
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import pytest

from .conftest import run_cli, skip_without_docling

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_FIXTURES_DIR = Path(__file__).parent / "fixtures"

#: Canned text description returned by the mock vision server.
CANNED_DESCRIPTION = "A bar chart showing quarterly sales performance for 2025."

#: Canned Mermaid diagram returned by the mock vision server.
CANNED_MERMAID = (
    "```mermaid\nflowchart TD\n    A[Start] --> B[Process] --> C[End]\n```"
)

_MOCK_PROMPT_TOKENS = 150
_MOCK_COMPLETION_TOKENS = 75

# ---------------------------------------------------------------------------
# Mock server
# ---------------------------------------------------------------------------


class _MockOpenAIHandler(BaseHTTPRequestHandler):
    """Minimal HTTP handler that returns canned OpenAI-style chat completions.

    Class-level attributes are mutated by :class:`MockVisionServer` to
    configure per-test responses and track invocation counts.
    """

    # Per-server-session configuration (set in MockVisionServer.__enter__)
    response_body: str = CANNED_DESCRIPTION
    #: Shared call counter — a one-element list so mutations are visible
    #: across the class hierarchy without needing instance state.
    call_counter: list[int] = [0]

    def do_POST(self) -> None:  # noqa: N802
        """Handle POST /v1/chat/completions with a canned response."""
        content_length = int(self.headers.get("Content-Length", 0))
        self.rfile.read(content_length)  # consume request body

        _MockOpenAIHandler.call_counter[0] += 1

        body = json.dumps(
            {
                "id": "chatcmpl-mock-e2e",
                "object": "chat.completion",
                "created": int(time.time()),
                "model": "mock-vision",
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": _MockOpenAIHandler.response_body,
                        },
                        "finish_reason": "stop",
                        "logprobs": None,
                    }
                ],
                "usage": {
                    "prompt_tokens": _MOCK_PROMPT_TOKENS,
                    "completion_tokens": _MOCK_COMPLETION_TOKENS,
                    "total_tokens": _MOCK_PROMPT_TOKENS + _MOCK_COMPLETION_TOKENS,
                },
            }
        ).encode()

        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format: str, *args: object) -> None:  # noqa: A002
        """Suppress default HTTP request logging."""


class MockVisionServer:
    """Context manager for a local mock OpenAI-compatible LLM server.

    Starts an :class:`~http.server.HTTPServer` on a random free port that
    accepts any POST request and replies with a canned OpenAI chat-completion
    JSON body.  Both text-enrichment and vision LLM calls from the nest
    subprocess are routed through this server.

    Usage::

        with MockVisionServer(response=CANNED_DESCRIPTION) as server:
            result = run_cli(["sync"], cwd=project_dir, env=server.env_vars())
        assert server.call_count > 0
    """

    def __init__(self, response: str = CANNED_DESCRIPTION) -> None:
        self._response = response
        self._server: HTTPServer | None = None
        self._thread: threading.Thread | None = None
        self.port: int = 0

    def __enter__(self) -> "MockVisionServer":
        # Reset shared call counter for this server session.
        _MockOpenAIHandler.call_counter[0] = 0

        # Build a per-invocation handler subclass so each MockVisionServer
        # context can use a different response body.
        handler_cls = type(
            "_Handler",
            (_MockOpenAIHandler,),
            {"response_body": self._response},
        )

        self._server = HTTPServer(("127.0.0.1", 0), handler_cls)
        self.port = self._server.server_address[1]
        self._thread = threading.Thread(
            target=self._server.serve_forever, daemon=True
        )
        self._thread.start()
        return self

    def __exit__(self, *_args: object) -> None:
        if self._server is not None:
            self._server.shutdown()

    @property
    def call_count(self) -> int:
        """Total API calls received by this server session."""
        return _MockOpenAIHandler.call_counter[0]

    def env_vars(self) -> dict[str, str]:
        """Env vars that route subprocess AI calls to this mock server.

        Both ``NEST_AI_*`` and ``OPENAI_*`` vars are set (with ``NEST_AI_*``
        taking priority in the nest fallback chain) so the subprocess uses the
        mock credentials regardless of the existing shell environment.
        """
        return {
            "NEST_AI_API_KEY": "mock-api-key-for-e2e-testing",
            "NEST_AI_ENDPOINT": f"http://127.0.0.1:{self.port}/v1",
            "NEST_AI_VISION_MODEL": "mock-vision-model",
            "NEST_AI_MODEL": "mock-text-model",
        }


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _put_image_fixture_in_project(project_dir: Path) -> Path:
    """Copy ``image_doc.pdf`` fixture into ``_nest_sources/`` of the project."""
    dest = project_dir / "_nest_sources" / "image_doc.pdf"
    shutil.copy(_FIXTURES_DIR / "image_doc.pdf", dest)
    return dest


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


@pytest.mark.e2e
class TestImageDescriptionE2E:
    """E2E tests for vision-based image description (Story 7.5).

    All tests use real Docling processing via subprocess CLI invocation.
    Vision LLM calls are intercepted by :class:`MockVisionServer`.
    """

    @skip_without_docling
    def test_image_description_produces_canned_description_in_output(
        self, initialized_project: Path
    ) -> None:
        """AC: Image description mode writes LLM text into the output markdown.

        Given a PDF with an embedded image and a mocked vision LLM,
        when nest sync runs,
        then the output markdown contains the canned description text
        and the sync summary includes 'Images described:'.
        """
        project_dir = initialized_project
        _put_image_fixture_in_project(project_dir)

        with MockVisionServer(response=CANNED_DESCRIPTION) as server:
            result = run_cli(
                ["sync"], cwd=project_dir, timeout=300, env=server.env_vars()
            )

        assert result.exit_code == 0, (
            f"Sync failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )

        output_md = project_dir / "_nest_context" / "image_doc.md"
        assert output_md.exists(), (
            "Expected '_nest_context/image_doc.md' to be created after sync"
        )
        content = output_md.read_text()
        assert CANNED_DESCRIPTION in content, (
            f"Expected canned description in output markdown.\n"
            f"stdout: {result.stdout}\n"
            f"Markdown (first 600 chars): {content[:600]}"
        )
        assert "Images described:" in result.stdout, (
            f"Expected 'Images described:' in sync summary.\nstdout: {result.stdout}"
        )

    @skip_without_docling
    def test_mermaid_response_appears_as_mermaid_block_in_output(
        self, initialized_project: Path
    ) -> None:
        """AC: Vision LLM mermaid response is preserved verbatim in markdown output.

        Given a mocked vision LLM that returns a fenced mermaid code block,
        when nest sync runs on a PDF with an image,
        then the output markdown contains a ```mermaid block with diagram elements.
        """
        project_dir = initialized_project
        _put_image_fixture_in_project(project_dir)

        with MockVisionServer(response=CANNED_MERMAID) as server:
            result = run_cli(
                ["sync"], cwd=project_dir, timeout=300, env=server.env_vars()
            )

        assert result.exit_code == 0, (
            f"Sync failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )

        output_md = project_dir / "_nest_context" / "image_doc.md"
        assert output_md.exists()
        content = output_md.read_text()
        assert "```mermaid" in content, (
            f"Expected mermaid code block in output.\n"
            f"Markdown (first 600 chars): {content[:600]}"
        )
        assert "flowchart TD" in content, (
            f"Expected mermaid diagram elements in output.\n"
            f"Markdown (first 600 chars): {content[:600]}"
        )

    @skip_without_docling
    def test_no_ai_env_vars_produces_image_placeholder(
        self, initialized_project: Path
    ) -> None:
        """AC: Without AI credentials, image output contains <!-- image --> placeholder.

        Given no AI API keys are configured,
        when nest sync runs on a PDF with an image,
        then the output markdown uses the Docling placeholder (<!-- image -->)
        and no description text is present.
        """
        project_dir = initialized_project
        _put_image_fixture_in_project(project_dir)

        # Override any ambient API keys with empty strings.
        # run_cli merges over os.environ, so empty-string values shadow real keys.
        # create_vision_provider() treats an empty string as "no key" (falsy).
        result = run_cli(
            ["sync"],
            cwd=project_dir,
            timeout=300,
            env={"NEST_AI_API_KEY": "", "OPENAI_API_KEY": ""},
        )

        assert result.exit_code == 0, (
            f"Sync failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )

        output_md = project_dir / "_nest_context" / "image_doc.md"
        assert output_md.exists()
        content = output_md.read_text()
        assert "<!-- image -->" in content, (
            f"Expected '<!-- image -->' placeholder in no-AI output.\n"
            f"Markdown (first 600 chars): {content[:600]}"
        )
        assert CANNED_DESCRIPTION not in content, (
            "Expected no description text in output without AI vision configured"
        )
        assert "Images described:" not in result.stdout, (
            f"Expected no 'Images described:' line without AI.\nstdout: {result.stdout}"
        )

    @skip_without_docling
    def test_no_ai_flag_produces_image_placeholder_and_no_vision_calls(
        self, initialized_project: Path
    ) -> None:
        """AC: --no-ai flag disables vision even when AI env vars are configured.

        Given AI env vars point at the mock server,
        when nest sync --no-ai runs,
        then the output uses <!-- image --> placeholders
        and zero calls are made to the mock (vision) server.
        """
        project_dir = initialized_project
        _put_image_fixture_in_project(project_dir)

        with MockVisionServer(response=CANNED_DESCRIPTION) as server:
            result = run_cli(
                ["sync", "--no-ai"],
                cwd=project_dir,
                timeout=300,
                env=server.env_vars(),
            )
            calls_with_no_ai_flag = server.call_count

        assert result.exit_code == 0, (
            f"Sync failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )

        output_md = project_dir / "_nest_context" / "image_doc.md"
        assert output_md.exists()
        content = output_md.read_text()
        assert "<!-- image -->" in content, (
            f"Expected '<!-- image -->' placeholder with --no-ai.\n"
            f"Markdown (first 600 chars): {content[:600]}"
        )
        assert CANNED_DESCRIPTION not in content, (
            "Expected no description text with --no-ai flag"
        )
        assert calls_with_no_ai_flag == 0, (
            f"Expected zero mock server calls with --no-ai, got {calls_with_no_ai_flag}"
        )

    @skip_without_docling
    def test_token_reporting_includes_vision_tokens(
        self, initialized_project: Path
    ) -> None:
        """AC: Sync summary 'AI tokens:' line aggregates vision description tokens.

        Given image descriptions are generated via the mocked vision LLM,
        when nest sync completes,
        then stdout includes an 'AI tokens:' line with non-zero token counts.
        """
        project_dir = initialized_project
        _put_image_fixture_in_project(project_dir)

        with MockVisionServer(response=CANNED_DESCRIPTION) as server:
            result = run_cli(
                ["sync"], cwd=project_dir, timeout=300, env=server.env_vars()
            )

        assert result.exit_code == 0, (
            f"Sync failed:\nstdout: {result.stdout}\nstderr: {result.stderr}"
        )
        assert "AI tokens:" in result.stdout, (
            f"Expected 'AI tokens:' in sync summary.\nstdout: {result.stdout}"
        )

    @skip_without_docling
    def test_incremental_sync_skips_unchanged_file_and_makes_no_vision_calls(
        self, initialized_project: Path
    ) -> None:
        """AC: Second sync on an unchanged PDF skips processing and makes no LLM calls.

        Given the first sync has already produced image descriptions,
        when nest sync runs again without any source-file changes,
        then the file is skipped (checksum match)
        and the mock server receives no additional calls.
        """
        project_dir = initialized_project
        _put_image_fixture_in_project(project_dir)

        with MockVisionServer(response=CANNED_DESCRIPTION) as server:
            # First sync: converts PDF and describes images.
            first = run_cli(
                ["sync"], cwd=project_dir, timeout=300, env=server.env_vars()
            )
            assert first.exit_code == 0, (
                f"First sync failed:\nstdout: {first.stdout}\nstderr: {first.stderr}"
            )
            calls_after_first = server.call_count
            assert calls_after_first > 0, (
                "Expected at least one mock server call during the first sync"
            )

            # Second sync: source unchanged — file skipped, no vision calls.
            second = run_cli(
                ["sync"], cwd=project_dir, timeout=300, env=server.env_vars()
            )
            assert second.exit_code == 0, (
                f"Second sync failed:\nstdout: {second.stdout}\nstderr: {second.stderr}"
            )
            calls_after_second = server.call_count

        assert calls_after_second == calls_after_first, (
            f"Expected no additional server calls on second sync (unchanged file), "
            f"but call count increased from {calls_after_first} to {calls_after_second}"
        )

        # Descriptions from the first sync are preserved in the output.
        output_md = project_dir / "_nest_context" / "image_doc.md"
        assert output_md.exists()
        content = output_md.read_text()
        assert CANNED_DESCRIPTION in content, (
            "Expected canned description to be preserved after incremental sync"
        )
