"""Tests for orphan detection logic.

Tests the OrphanDetector class for identifying orphaned output files.

The new orphan logic only marks files as orphans if:
1. They ARE in the manifest (generated by Nest)
2. Their source file no longer exists

Files NOT in the manifest are user-curated and should be preserved.
"""

from pathlib import Path
from unittest.mock import patch

from nest.core.orphan_detector import OrphanDetector


class TestOrphanDetector:
    """Tests for OrphanDetector class."""

    def test_detects_orphan_when_source_file_missing(self) -> None:
        """Verify orphan detection when source file no longer exists."""
        detector = OrphanDetector()
        output_dir = Path("/project/_nest_context")
        output_files = [
            Path("/project/_nest_context/valid.md"),
            Path("/project/_nest_context/orphan.md"),
        ]
        # manifest_sources: source_path -> output_relative
        # valid.pdf exists, orphan_source.pdf does not exist
        manifest_sources = {
            Path("/project/_nest_sources/valid.pdf"): "valid.md",
            Path("/project/_nest_sources/orphan_source.pdf"): "orphan.md",
        }

        with patch.object(Path, "exists") as mock_exists:
            # valid.pdf exists, orphan_source.pdf does not
            mock_exists.side_effect = lambda: False  # Default

            def exists_check(self):
                return "valid.pdf" in str(self)

            with patch.object(Path, "exists", exists_check):
                orphans = detector.detect(output_files, manifest_sources, output_dir)

        assert len(orphans) == 1
        assert Path("/project/_nest_context/orphan.md") in orphans

    def test_no_orphans_when_all_sources_exist(self) -> None:
        """Verify no orphans detected when all source files exist."""
        detector = OrphanDetector()
        output_dir = Path("/project/_nest_context")
        output_files = [
            Path("/project/_nest_context/file1.md"),
            Path("/project/_nest_context/file2.md"),
        ]
        manifest_sources = {
            Path("/project/_nest_sources/file1.pdf"): "file1.md",
            Path("/project/_nest_sources/file2.pdf"): "file2.md",
        }

        with patch.object(Path, "exists", return_value=True):
            orphans = detector.detect(output_files, manifest_sources, output_dir)

        assert len(orphans) == 0

    def test_excludes_master_index_from_orphans(self) -> None:
        """Verify 00_MASTER_INDEX.md is never considered an orphan."""
        detector = OrphanDetector()
        output_dir = Path("/project/_nest_context")
        output_files = [
            Path("/project/_nest_context/00_MASTER_INDEX.md"),
        ]
        manifest_sources: dict[Path, str] = {}  # Empty manifest

        orphans = detector.detect(output_files, manifest_sources, output_dir)

        assert len(orphans) == 0

    def test_user_curated_files_not_orphans(self) -> None:
        """Verify files NOT in manifest (user-curated) are never orphans."""
        detector = OrphanDetector()
        output_dir = Path("/project/_nest_context")
        output_files = [
            Path("/project/_nest_context/user-guide.md"),  # Not in manifest
            Path("/project/_nest_context/tracked.md"),  # In manifest, source exists
        ]
        manifest_sources = {
            Path("/project/_nest_sources/tracked.pdf"): "tracked.md",
        }

        with patch.object(Path, "exists", return_value=True):
            orphans = detector.detect(output_files, manifest_sources, output_dir)

        # user-guide.md is NOT an orphan because it's not in manifest
        assert len(orphans) == 0

    def test_empty_output_directory(self) -> None:
        """Verify handles empty output directory."""
        detector = OrphanDetector()
        output_dir = Path("/project/_nest_context")
        output_files: list[Path] = []
        manifest_sources = {
            Path("/project/_nest_sources/file.pdf"): "file.md",
        }

        orphans = detector.detect(output_files, manifest_sources, output_dir)

        assert len(orphans) == 0

    def test_multiple_orphans_from_missing_sources(self) -> None:
        """Verify detection of multiple orphan files when sources missing."""
        detector = OrphanDetector()
        output_dir = Path("/project/_nest_context")
        output_files = [
            Path("/project/_nest_context/valid.md"),
            Path("/project/_nest_context/orphan1.md"),
            Path("/project/_nest_context/orphan2.md"),
            Path("/project/_nest_context/subdir/orphan3.md"),
        ]
        manifest_sources = {
            Path("/project/_nest_sources/valid.pdf"): "valid.md",
            Path("/project/_nest_sources/orphan1.pdf"): "orphan1.md",
            Path("/project/_nest_sources/orphan2.pdf"): "orphan2.md",
            Path("/project/_nest_sources/subdir/orphan3.pdf"): "subdir/orphan3.md",
        }

        def exists_check(self):
            return "valid.pdf" in str(self)

        with patch.object(Path, "exists", exists_check):
            orphans = detector.detect(output_files, manifest_sources, output_dir)

        assert len(orphans) == 3
        assert Path("/project/_nest_context/orphan1.md") in orphans
        assert Path("/project/_nest_context/orphan2.md") in orphans
        assert Path("/project/_nest_context/subdir/orphan3.md") in orphans
