"""Orphan detection logic.

Detects orphaned output files that no longer have corresponding source files.
"""

from pathlib import Path


class OrphanDetector:
    """Detects orphaned output files with no corresponding source."""

    def detect(
        self,
        output_files: list[Path],
        manifest_sources: dict[Path, str],
        output_dir: Path,
    ) -> list[Path]:
        """Find output files tracked in manifest but with missing source files.

        A file is an orphan ONLY if:
        1. It IS in the manifest (generated by Nest)
        2. Its source file no longer exists
        
        Files NOT in the manifest are user-curated and should be preserved.

        Args:
            output_files: All files in context directory.
            manifest_sources: Dict mapping source paths to their output paths (from manifest).
            output_dir: Base output directory for relative path computation.

        Returns:
            List of orphan file paths (absolute) to remove.
        """
        # Build reverse lookup: output_path -> source_path
        output_to_source: dict[str, Path] = {}
        for source_path, output_relative in manifest_sources.items():
            output_to_source[output_relative] = source_path
        
        orphans: list[Path] = []

        for file_path in output_files:
            relative = file_path.relative_to(output_dir).as_posix()

            # Exclude system files
            if relative == "00_MASTER_INDEX.md":
                continue

            # Check if file is in manifest
            if relative in output_to_source:
                # File is in manifest - check if source exists
                source_path = output_to_source[relative]
                if not source_path.exists():
                    # Source is missing - this is an orphan
                    orphans.append(file_path)
            # else: File NOT in manifest = user-curated, not an orphan

        return orphans
